# Generated by Django 3.2.14 on 2022-07-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='RecipeIngredient', to='recipe.Ingridients', verbose_name='Ингридиенты'),
        ),
    ]
